language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      
jdk:
  - oraclejdk8
  
service:
  - mysql

before_script:
  - mysql -u guestbook -p -e 'create database guestbook;'
  - $pass

script:
        - cd $TRAVIS_BUILD_DIR/guestbook
        - mvn test

notifications:
  email: false
